server:
  port: 9997
spring:
  application:
    name: xiaoxiao-sso
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://dk-xiaoxiao.com:9999/eureka/
COOKIE_NAME: USER

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
