server:
  port: 9995
spring:
  application:
    name: xiaoxiao-search
  datasource:
    username: root
    password: 159302
    url: jdbc:mysql://dk-xiaoxiao.com:9178/xiaoxiao_borker?characterEncoding=UTF-8
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    core: blog
    solr:
      host: http://dk-xiaoxiao.com:9995/solr
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://dk-xiaoxiao.com:9999/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000